###
# @name Get Public Spots without query Param
#
GET {{base-path}}/spots

###
# @name Get Public Spots
#
GET {{base-path}}/spots?includeAll=false

###
# @name Get All Spots
#
GET {{base-path}}/spots?includeAll=true


